blank_issues_enabled: false
contact_links:
  - name: Github Discussions
    url: https://github.com/RetroArcher/RetroArcher.bundle/discussions
    about: General discussion, support, feature requests and more!
  - name: Discord support
    url: https://discord.gg/d6MpcrbYQs
    about: Ask question about RetroArcher in Discord
  - name: Reddit support
    url: https://www.reddit.com/r/RetroArcher
    about: Ask questions about RetroArcher on Reddit
  - name: Facebook support
    url: https://www.facebook.com/groups/retroracher
    about: Ask question about RetroArcher on Facebook
  - name: Feature request
    url: https://retroarcher.github.io/featurereq
    about: Share your suggestions or ideas to make RetroArcher better!
