name: CI

on:
  pull_request:
    branches: [master, nightly]
    types: [opened, synchronize, edited, reopened]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  check_changelog:
    name: Check Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify Changelog
      id: verify_changelog
      if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
      # base_ref for pull request check, ref for push
      uses: RetroArcher/actions/verify_changelog@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      next_version: ${{ steps.verify_changelog.outputs.changelog_parser_version }}
      last_version: ${{ steps.verify_changelog.outputs.latest_release_tag_name }}
      release_body:  ${{ steps.verify_changelog.outputs.changelog_parser_description }}

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-10.15]

    runs-on: ${{ matrix.os }}
    needs: check_changelog

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: RetroArcher.bundle

      - name: Install Python 2.7
        uses: actions/setup-python@v3  # https://github.com/actions/setup-python
        with:
          python-version: '2.7'

      - name: Set up Python 2.7 Dependencies
        env:
          TARGET_DIR: ./RetroArcher.bundle/Contents/Libraries/Shared
        run: |
          echo "Installing Plex Agent Requirements"
          python --version
          python -m pip --no-python-version-warning --disable-pip-version-check install --upgrade pip==20.3.4 setuptools
          python -m pip --no-python-version-warning --disable-pip-version-check install --upgrade 'requests<2.28'
          python -m pip --no-python-version-warning --disable-pip-version-check install --target=${{ env.TARGET_DIR }} -r ${{ env.TARGET_DIR }}/requirements.txt --no-warn-script-location --ignore-requires-python

      - name: Test Plex Agent
        env:
          TARGET_DIR: ./Contents/Code
        run: |
          cd RetroArcher.bundle
          python --version
          python ${{ env.TARGET_DIR }}/__init__.py

      - name: Install Python 3.9
        uses: actions/setup-python@v3  # https://github.com/actions/setup-python
        with:
          python-version: '3.9'

      - name: Build plist
        env:
          BUILD_VERSION: ${{ needs.check_changelog.outputs.next_version }}
        run: |
          cd RetroArcher.bundle
          python scripts/build_plist.py

      - name: Set up Python 3.9 Dependencies
        env:
          TARGET_DIR: ./RetroArcher.bundle/Contents/Libraries/Modules
        run: |
          echo "Installing RetroArcher Requirements"
          python --version
          python -m pip install --upgrade pip setuptools
          python -m pip install --target=${{ env.TARGET_DIR }} -r ${{ env.TARGET_DIR }}/requirements.txt --no-warn-script-location

#      - name: Overwrite ADB Binaries
#        run: |
#          echo "Overwriting Latest ADB Binaries"
#          cd RetroArcher.bundle
#          python -m pip install -r scripts/requirements.txt
#          python scripts/download_adb_binaries.py

      - name: Test RetroArcher
        env:
          TARGET_DIR: ./Contents/Code/retroarcher
        run: |
          cd RetroArcher.bundle
          python --version
          python ${{ env.TARGET_DIR }}/retroarcher.py

      - name: Upload Artifacts
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3  # https://github.com/actions/upload-artifact
        with:
          name: RetroArcher.bundle-${{ runner.os }}
          if-no-files-found: error  # 'warn' or 'ignore' are also available, defaults to `warn`
          path: |
            ${{ github.workspace }}
            !**/*.git*
            !**/*.pyc
            !**/__pycache__
            !**/RetroArcher.bundle/scripts

      - name: Package Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          7z "-xr!*.git*" "-xr!*.pyc" "-xr!__pycache__" "-x!scripts" a "./RetroArcher.bundle-${{ runner.os }}.zip" "RetroArcher.bundle"

      - name: Create/Update GitHub Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: ncipollo/release-action@v1  # https://github.com/ncipollo/release-action
        with:
          name: ${{ needs.check_changelog.outputs.next_version }}
          tag: ${{ needs.check_changelog.outputs.next_version }}
          artifacts: "*.zip"
          token: ${{ secrets.GH_PAT }}
          allowUpdates: true
          body: ${{ needs.check_changelog.outputs.release_body }}
          discussionCategory: Announcements
