name: Create Package

on:
  pull_request:
    branches: [master, nightly]
    types: [opened, synchronize, edited, reopened]
  push:
    branches: [master, nightly, add-repo-actions]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - name: Set up Python 2.7 Dependencies
        run: |
          echo "Installing Plex Agent Requirements"
          echo Contents\Libraries\Shared >> $env:TARGET_DIR
          python --version
          python -m pip install --upgrade pip==20.3.4
          pip install --target=${{ env.TARGET_DIR }} -r ${{ env.TARGET_DIR }}\requirements.txt
      - name: Test Plex Agent
        run: |
          python --version
          python Contents\Code\__init__.py
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Set up Python 3.9 Dependencies
        run: |
          echo "Installing RetroArcher Requirements"
          echo Contents\Libraries\Modules >> $env:TARGET_DIR
          python --version
          python -m pip install --upgrade pip
          pip install --target=${{ env.TARGET_DIR }} -r ${{ env.TARGET_DIR }}\requirements.txt
      - name: Test RetroArcher
        run: |
          python --version
          python Contents\Code\retroarcher\retroarcher.py
      - name: Workflow Info
        run: |
          echo Event Name: $GITHUB_EVENT_NAME
      - name: Upload Artifacts
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v2
        with:
          name: RetroArcher.bundle
          path: /**
