name: Pull Requests

on:
  pull_request_target:
    types: [opened, synchronize, edited, reopened]

jobs:
  check-pull-request:
    name: Check Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: master
          exclude: nightly # Don't prevent going from nightly -> master
          change-to: nightly
          comment: |
              Your PR was set to `master`, PRs should be sent to `nightly`
              The base branch of this PR has been automatically changed to `nightly`, please check that there are no merge conflicts
