name: Release Notifications

on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner


      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'

      - name: install python requirements
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/ReenigneArcher/release_notifier.git

      - name: release_notifier
        env:
          DISCORD_WEBHOOKS: ${{ secrets.DISCORD_WEBHOOKS }}
          FACEBOOK_IDS: ${{ secrets.FACEBOOK_IDS }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_SUBREDDITS: ${{ secrets.REDDIT_SUBREDDITS }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run:
          release_notifier.py --discord --facebook --reddit --twitter
